[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200

[build]
  # 👇 Force legacy-peer-deps to resolve CMS + React 18 mismatch
  command = "npm install --legacy-peer-deps && next build"
  publish = ".next"
