# Force all traffic to https://www
[[redirects]]
  from = "http://kebbidailynews.com/*"
  to = "https://www.kebbidailynews.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.kebbidailynews.com/*"
  to = "https://www.kebbidailynews.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://kebbidailynews.com/*"
  to = "https://www.kebbidailynews.com/:splat"
  status = 301
  force = true

# Keep your admin redirect
[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200

[build]
  command = "next build"
  publish = ".next"