backend:
  name: git-gateway
  branch: main # Change to your production branch
local_backend: true # Enable local CMS testing
media_folder: "public/uploads"
public_folder: "/uploads"
collections:
  - name: "news"
    label: "News"
    folder: "content/news"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string", required: true }
      - { label: "Excerpt", name: "excerpt", widget: "string", required: true }
      - { label: "Date", name: "date", widget: "datetime", required: true }
      - { label: "Image", name: "image", widget: "image", required: false }
      - { label: "Content", name: "content", widget: "markdown", required: true }